---
# Globals
exclude: >
  ^(
    docs/|
    src/|
    \.git/|
    \.github/.*|
    \.venv/|
    .idea/|
    \.vscode/|
    manage\.py$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        description: "Removes trailing whitespace"
      - id: end-of-file-fixer
        description: "Ensures files end with a newline"
      - id: check-added-large-files
        description: "Prevent large files from being added to the repo"
        args: ["--maxkb=500"]
        exclude: >
          ^docs/|
          ^src/|
          ^\.git/|
          ^\.github/.*|
          ^\.venv/|
          .idea/|
          ^\.vscode/|
          manage\.py$
      # - id: check-docstring-first
      #   description: "Ensure docstrings are the first statement in functions,\
      # classes, and modules"

  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
      - id: black
        args: ["--line-length=100"]
        description: "Formats code to adhere to PEP8 standards"

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2  # Use the latest stable version
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]
        description: "Sorts imports automatically"

  # Find a way to resolve the false negatives
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.1  # Use the latest stable version
  #   hooks:
  #     - id: flake8
  #       args: ["--max-line-length=100", "--ignore=E203,W503"]
  #       description: "Checks for linting issues"
  #       additional_dependencies:
  #         # - flake8-docstrings  # Linting for docstrings
  #         - flake8-bugbear     # Detects common mistakes
  #         - flake8-comprehensions  # Ensures optimal list comprehensions

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0  # Use the latest stable version
  #   hooks:
  #     - id: mypy
  #       args: ["--ignore-missing-imports"]
  #       description: "Checks for type issues in the codebase"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
        description: "Warns against blanket noqa directives"
      - id: python-no-eval
        description: "Disallows the use of eval() in Python code"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0  # Replace with the correct version from the repository
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
        description: "Upgrades Python syntax to modern versions"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        description: "Lints YAML files"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        description: "Prevent committing private keys"
